[build]
builder = "NIXPACKS"
nixpacksVersion = "1.21.0"

[build.env]
NODE_VERSION = "20"

[deploy]
startCommand = "npm run start:prod"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_ENV = "production"